name: Coderco

on: [push]


jobs:
  build:
  runs-on: ubuntu latest

  strategy:
    matrix:
      python-version: [3.10, 3.8, 3.9]


  steps:
  - name: checkout
    uses: actions/checkout@v2
  

  - name: set up python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ matrix.python-version }}

  - name: install dependencies 
    run: |
      cd chapter4 
      python -m pip install --upgrade pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  - name: run test 
    run: |
      cd chapter4
      python -m unittest discover 
  
  - name: notify us of the sucessful stage 
    run: echo "tests passed on python ${{matrix.python-version}}"
    if: sucess()